version: '3'
services: 
    cashback_app:
        build: .
        container_name: cashback_app
        command: bundle exec rails s -b 0.0.0.0
        volumes:
            - ./:/app/
        ports:
            - 3000:3000
        depends_on: 
            - database
        env_file: 
            - .env
    
    database:
        image: postgres:latest
        volumes: 
            - ./data/psql/:/var/lib/postgresql/
        ports:
            - 5432:5432            
        env_file: 
            - .env
        